# -*- coding: utf-8 -*-
"""Predicting F1 Pitstops Challenge Kaggle

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TjwSJtTYr5g0HRgM2ytm3nV6O9APn3IY
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install catboost

import pandas as pd

train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/kaggle/f1pitstops/train.csv')
test  = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/kaggle/f1pitstops/test.csv')
sub   = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/kaggle/f1pitstops/sample_submission.csv')

print(train.shape)
print(test.shape)
print(sub.shape)

import pandas as pd

# Combine unique 'Race' values from train and test datasets
all_races = pd.concat([train['Race'], test['Race']]).unique()

print("Unique Circuit Names:")
for race in sorted(all_races):
    print(f"- {race}")

import os
import gc
import warnings
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.metrics import roc_auc_score
from sklearn.isotonic import IsotonicRegression
from sklearn.linear_model import BayesianRidge

import lightgbm as lgb
from lightgbm import early_stopping, log_evaluation
import xgboost as xgb
from catboost import CatBoostClassifier, Pool

warnings.filterwarnings("ignore")

# ==========================================
# 1. CONFIGURATION & DATA LOADING
# ==========================================
SEED = 2024
N_FOLDS = 5
TARGET = "PitNextLap"

print("Loading data...")
train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/kaggle/f1pitstops/train.csv')
test  = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/kaggle/f1pitstops/test.csv')

# Ensure strings are stripped and clean
for col in ["Driver", "Race", "Compound"]:
    train[col] = train[col].astype(str).str.strip().str.upper()
    test[col]  = test[col].astype(str).str.strip().str.upper()

train["is_test"] = 0
test["is_test"] = 1
test[TARGET] = np.nan

combined = pd.concat([train, test], axis=0, ignore_index=True)
print(f"Combined data shape: {combined.shape}")

# ==========================================
# 2. BASIC FEATURE ENGINEERING
# ==========================================
COMPOUND_ORDER = {"WET": 0, "INTERMEDIATE": 1, "SOFT": 2, "MEDIUM": 3, "HARD": 4}
combined["Compound_ord"] = combined["Compound"].map(COMPOUND_ORDER)
combined["RaceYear"] = combined["Race"] + "_" + combined["Year"].astype(str)

combined["TotalLaps_est"] = (combined["LapNumber"] / combined["RaceProgress"].replace(0, np.nan)).round()
combined["LapsRemaining"] = combined["TotalLaps_est"] - combined["LapNumber"]

# ==========================================
# 3. DOMAIN KNOWLEDGE INTEGRATION
# ==========================================

# A. Dynamic Track Degradation & Max Stint
race_degradation = {
    'CANADIAN GRAND PRIX': 'Medium', 'DUTCH GRAND PRIX': 'Medium',
    'AUSTRIAN GRAND PRIX': 'Medium', 'AZERBAIJAN GRAND PRIX': 'Low',
    'SAUDI ARABIAN GRAND PRIX': 'Medium', 'BELGIAN GRAND PRIX': 'Medium',
    'UNITED STATES GRAND PRIX': 'Medium', 'ITALIAN GRAND PRIX': 'Low',
    'HUNGARIAN GRAND PRIX': 'Medium', 'JAPANESE GRAND PRIX': 'High',
    'SÃO PAULO GRAND PRIX': 'Medium', 'BAHRAIN GRAND PRIX': 'High',
    'LAS VEGAS GRAND PRIX': 'Low', 'MONACO GRAND PRIX': 'Low',
    'BRITISH GRAND PRIX': 'Medium', 'AUSTRALIAN GRAND PRIX': 'Medium',
    'SPANISH GRAND PRIX': 'Medium', 'MIAMI GRAND PRIX': 'Low',
    'FRENCH GRAND PRIX': 'Medium', 'ABU DHABI GRAND PRIX': 'Low',
    'CHINESE GRAND PRIX': 'Medium', 'MEXICO CITY GRAND PRIX': 'High',
    'EMILIA ROMAGNA GRAND PRIX': 'Medium', 'SINGAPORE GRAND PRIX': 'Low',
    'QATAR GRAND PRIX': 'High'
}

def get_deg_level(row):
    race = row['Race']
    if race == 'PRE-SEASON TESTING':
        return 'High' if row['Year'] >= 2021 else 'Medium'
    return race_degradation.get(race, 'Medium')

combined['Degradation_Level'] = combined.apply(get_deg_level, axis=1)
deg_multipliers = {'Low': 1.2, 'Medium': 1.0, 'High': 0.8}
combined['Deg_Multiplier'] = combined['Degradation_Level'].map(deg_multipliers)

COMPOUND_MAX_STINT = {"SOFT": 25, "MEDIUM": 35, "HARD": 50, "INTERMEDIATE": 30, "WET": 40}
combined["Base_MaxStint"] = combined["Compound"].map(COMPOUND_MAX_STINT)
combined["MaxStint"] = combined["Base_MaxStint"] * combined["Deg_Multiplier"]
combined["TyrePct_Used"] = (combined["TyreLife"] / combined["MaxStint"]).clip(0, 2)

# B. SC / VSC Detection (>40% pace drop)
race_lap_medians = combined.groupby(['RaceYear', 'LapNumber'])['LapTime (s)'].median().reset_index()
race_lap_medians.rename(columns={'LapTime (s)': 'Field_Median_LapTime'}, inplace=True)
race_lap_medians = race_lap_medians.sort_values(['RaceYear', 'LapNumber'])
race_lap_medians['Prev_Lap_Median'] = race_lap_medians.groupby('RaceYear')['Field_Median_LapTime'].shift(1)
race_lap_medians['SC_VSC_Active'] = (race_lap_medians['Field_Median_LapTime'] >= 1.4 * race_lap_medians['Prev_Lap_Median']).astype(int)

combined = combined.merge(race_lap_medians[['RaceYear', 'LapNumber', 'Field_Median_LapTime', 'SC_VSC_Active']], on=['RaceYear', 'LapNumber'], how='left')
combined['SC_VSC_Active'] = combined['SC_VSC_Active'].fillna(0)

# C. Pit Lane Time Loss & Dynamic Undercut Window
pit_loss_times = {
    'CANADIAN GRAND PRIX': 18.4, 'BRITISH GRAND PRIX': 19.9, 'AUSTRIAN GRAND PRIX': 20.0,
    'ITALIAN GRAND PRIX': 20.0, 'MEXICO CITY GRAND PRIX': 21.9, 'AUSTRALIAN GRAND PRIX': 22.0,
    'SPANISH GRAND PRIX': 22.0, 'MONACO GRAND PRIX': 25.5, 'AZERBAIJAN GRAND PRIX': 28.0,
    'ABU DHABI GRAND PRIX': 28.0, 'SINGAPORE GRAND PRIX': 30.0
}
median_pit_loss = np.median(list(pit_loss_times.values()))
combined['Expected_Pit_Loss'] = combined['Race'].map(pit_loss_times).fillna(median_pit_loss)

def calculate_dynamic_pit_window(row):
    prog = row['RaceProgress']
    loss = row['Expected_Pit_Loss']
    if loss < 21.0: return 1 if ((0.15 <= prog <= 0.35) or (0.50 <= prog <= 0.70)) else 0
    elif loss > 24.0: return 1 if ((0.25 <= prog <= 0.45) or (0.60 <= prog <= 0.80)) else 0
    else: return 1 if ((0.20 <= prog <= 0.40) or (0.55 <= prog <= 0.75)) else 0

combined['InPitWindow'] = combined.apply(calculate_dynamic_pit_window, axis=1)

# D. Mandatory Two-Compound Rule
dry_compounds = ['SOFT', 'MEDIUM', 'HARD']
combined['Mandatory_Pit_Owed'] = ((combined['Stint'] == 1) & (combined['Compound'].isin(dry_compounds)) & (combined['RaceProgress'] >= 0.75)).astype(int)
combined['Mandatory_Pit_Urgency'] = np.where(combined['Mandatory_Pit_Owed'] == 1, (combined['RaceProgress'] - 0.75) / 0.25, 0.0)


# ==========================================
# 4. ROLLING & RELATIVE FEATURES
# ==========================================
combined.sort_values(["Driver", "RaceYear", "LapNumber"], inplace=True)
combined.reset_index(drop=True, inplace=True)
grp = combined.groupby(["Driver", "RaceYear"])

combined["TyreLife_x_RaceProgress"] = combined["TyreLife"] * combined["RaceProgress"]
combined["Degradation_per_Lap"] = (combined["Cumulative_Degradation"] / combined["TyreLife"].replace(0, 1)).clip(0, 10)
combined["TyreLife_vs_LapsRemaining"] = (combined["TyreLife"] / combined["LapsRemaining"].replace(0, 1)).clip(0, 10)
combined["Stint_x_Compound"] = combined["Stint"] * combined["Compound_ord"]
combined["LapsOverMaxStint"] = (combined["TyreLife"] - combined["MaxStint"]).clip(-50, 50)

combined["LapTime_roll3"] = grp["LapTime (s)"].transform(lambda x: x.rolling(3, min_periods=1).mean())
combined["Delta_roll3"] = grp["LapTime_Delta"].transform(lambda x: x.rolling(3, min_periods=1).mean())
combined["CumDeg_roll3"] = grp["Cumulative_Degradation"].transform(lambda x: x.rolling(3, min_periods=1).mean())
combined["LapTime_diff1"] = grp["LapTime (s)"].transform(lambda x: x.diff(1))
combined["LapTime_roll5"] = grp["LapTime (s)"].transform(lambda x: x.rolling(5, min_periods=1).mean())
combined["Delta_roll5"] = grp["LapTime_Delta"].transform(lambda x: x.rolling(5, min_periods=1).mean())
combined["LapTime_roll10"] = grp["LapTime (s)"].transform(lambda x: x.rolling(10, min_periods=1).mean())
combined["Delta_roll10"] = grp["LapTime_Delta"].transform(lambda x: x.rolling(10, min_periods=1).mean())

combined["PaceDropoff_3v10"] = combined["LapTime_roll3"] - combined["LapTime_roll10"]
combined["DegDropoff_3v10"]  = combined["Delta_roll3"] - combined["Delta_roll10"]
combined["Position_x_Lap"]  = combined["Position"] * combined["RaceProgress"]

combined["Pace_vs_Field"] = combined["LapTime (s)"] - combined["Field_Median_LapTime"]
combined["Is_Tyre_Cliff"] = (combined["LapTime_diff1"] > 2.0).astype(int)

# Delta to Personal Best
combined["Personal_Best_Lap"] = combined.groupby(["Driver", "RaceYear", "Stint"])["LapTime (s)"].cummin()
combined["Delta_to_Personal_Best"] = combined["LapTime (s)"] - combined["Personal_Best_Lap"]

# Pit Frenzy Tracker
pitted_last_lap = combined.groupby(["RaceYear", "LapNumber"])["PitStop"].sum().reset_index()
pitted_last_lap["LapNumber"] += 1
pitted_last_lap.rename(columns={"PitStop": "Cars_Pitted_Last_Lap"}, inplace=True)
combined = combined.merge(pitted_last_lap, on=["RaceYear", "LapNumber"], how="left")
combined["Cars_Pitted_Last_Lap"] = combined["Cars_Pitted_Last_Lap"].fillna(0)

# Sort back & Clean up NaNs
combined.sort_values(["Driver", "RaceYear", "LapNumber"], inplace=True)
combined.reset_index(drop=True, inplace=True)
combined.fillna(0, inplace=True) # Catch any rolling NAs

# ==========================================
# 5. SPLIT & TARGET ENCODING
# ==========================================
train_fe = combined[combined["is_test"] == 0].copy()
test_fe  = combined[combined["is_test"] == 1].copy()

TARGET_ENC_COLS = ["Driver", "Race", "RaceYear", "Compound"]
SMOOTH = 20
global_mean = train_fe[TARGET].mean()

for col in TARGET_ENC_COLS:
    train_fe[f"TE_{col}"] = 0.0
    test_fe[f"TE_{col}"] = 0.0

temp_sgkf = StratifiedGroupKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
for tr_idx, val_idx in temp_sgkf.split(train_fe, train_fe[TARGET], train_fe["RaceYear"]):
    tr_df, val_df = train_fe.iloc[tr_idx], train_fe.iloc[val_idx]
    for col in TARGET_ENC_COLS:
        agg = tr_df.groupby(col)[TARGET].agg(["mean", "count"])
        agg["te_smooth"] = (agg["count"] * agg["mean"] + SMOOTH * global_mean) / (agg["count"] + SMOOTH)
        train_fe.loc[train_fe.index[val_idx], f"TE_{col}"] = val_df[col].map(agg["te_smooth"]).fillna(global_mean)
        test_fe[f"TE_{col}"] += test_fe[col].map(agg["te_smooth"]).fillna(global_mean) / N_FOLDS

# ==========================================
# 6. MODELING & STACKING
# ==========================================
FEATURES = [
    "Year", "LapNumber", "Stint", "TyreLife", "Position", "LapTime (s)", "LapTime_Delta",
    "Cumulative_Degradation", "RaceProgress", "Position_Change", "PitStop", "Compound_ord",
    "TyrePct_Used", "MaxStint", "TotalLaps_est", "LapsRemaining", "TyreLife_x_RaceProgress",
    "Degradation_per_Lap", "TyreLife_vs_LapsRemaining", "Stint_x_Compound", "LapsOverMaxStint",
    "InPitWindow", "Expected_Pit_Loss", "LapTime_roll3", "Delta_roll3", "CumDeg_roll3",
    "LapTime_diff1", "LapTime_roll5", "Delta_roll5", "LapTime_roll10", "Delta_roll10",
    "PaceDropoff_3v10", "DegDropoff_3v10", "Position_x_Lap", "TE_Driver", "TE_Race",
    "TE_Compound", "TE_RaceYear", "Pace_vs_Field", "Is_Tyre_Cliff", "Delta_to_Personal_Best",
    "Cars_Pitted_Last_Lap", "SC_VSC_Active", "Mandatory_Pit_Owed", "Mandatory_Pit_Urgency"
]

X = train_fe[FEATURES].values
y = train_fe[TARGET].values.astype(int)
groups = train_fe["RaceYear"].values
X_test = test_fe[FEATURES].values

oof_lgb, test_lgb = np.zeros(len(X)), np.zeros(len(X_test))
oof_xgb, test_xgb = np.zeros(len(X)), np.zeros(len(X_test))
oof_cb,  test_cb  = np.zeros(len(X)), np.zeros(len(X_test))

sgkf = StratifiedGroupKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)

print("\nStarting Model Training...")
for fold, (tr_idx, val_idx) in enumerate(sgkf.split(X, y, groups), 1):
    print(f"--- Fold {fold} ---")
    X_tr, X_val = X[tr_idx], X[val_idx]
    y_tr, y_val = y[tr_idx], y[val_idx]

    # LightGBM
    dtrain_lgb = lgb.Dataset(X_tr, label=y_tr)
    dvalid_lgb = lgb.Dataset(X_val, label=y_val, reference=dtrain_lgb)
    model_lgb = lgb.train({"objective": "binary", "metric": "auc", "learning_rate": 0.02, "verbose": -1},
                          dtrain_lgb, num_boost_round=1500, valid_sets=[dvalid_lgb],
                          callbacks=[early_stopping(stopping_rounds=100, verbose=False)])

    oof_lgb[val_idx] = model_lgb.predict(X_val)
    test_lgb += model_lgb.predict(X_test) / N_FOLDS

    # XGBoost
    dtrain_xgb = xgb.DMatrix(X_tr, label=y_tr)
    dvalid_xgb = xgb.DMatrix(X_val, label=y_val)
    dtest_xgb  = xgb.DMatrix(X_test)
    model_xgb = xgb.train({"objective": "binary:logistic", "eval_metric": "auc", "learning_rate": 0.02},
                          dtrain_xgb, num_boost_round=1500, evals=[(dvalid_xgb, "val")],
                          early_stopping_rounds=100, verbose_eval=False)

    oof_xgb[val_idx] = model_xgb.predict(dvalid_xgb)
    test_xgb += model_xgb.predict(dtest_xgb) / N_FOLDS

    # CatBoost
    model_cb = CatBoostClassifier(iterations=1500, learning_rate=0.03, eval_metric="AUC", verbose=False)
    model_cb.fit(X_tr, y_tr, eval_set=(X_val, y_val), use_best_model=True)

    oof_cb[val_idx] = model_cb.predict_proba(X_val)[:, 1]
    test_cb += model_cb.predict_proba(X_test)[:, 1]

# Stacking Meta-Learner
print("\nTraining Stacking Meta-Learner (Bayesian Ridge)...")
oof_stack  = np.column_stack([oof_lgb, oof_xgb, oof_cb])
test_stack = np.column_stack([test_lgb, test_xgb, test_cb])

meta_model = BayesianRidge()
meta_model.fit(oof_stack, y)
meta_test_preds = np.clip(meta_model.predict(test_stack), 0.00001, 0.99999)

# Save Submission
submission = pd.DataFrame({'id': test['id'], 'PitNextLap': meta_test_preds})
submission.to_csv('submission.csv', index=False)
print("Pipeline complete. Saved to 'submission.csv'")

from sklearn.model_selection import cross_val_predict

# Generate cross-validated predictions for the meta-learner
meta_oof_preds = cross_val_predict(BayesianRidge(), oof_stack, y, cv=sgkf, groups=groups)

print(f"Stacked Meta-Model OOF ROC AUC: {roc_auc_score(y, meta_oof_preds):.5f}")